export type Color =
  | "primary"
  | "secondary"
  | "tiffany"
  | "purple"
  | "danger"
  | "success"
  | "warn"
  | "info"
  | "muted"
  | "light"
  | "gradient"
  | "dark"

export type Size = "xs" | "sm" | "md" | "lg" | "xl" | "full"
export type Radius = Size | "none"
export type Font = "thin" | "regular" | "heavy"
export type Role = "admin" | "user"
export type Shape = "square" | "rectangle" | "circle"
